const suitOptions = [
  {'label': 'Spades', 'value': 'spades'},
  {'label': 'Hearts', 'value': 'hearts'},
  {'label': 'Clubs', 'value': 'clubs'},
  {'label': 'Diamonds', 'value': 'diamonds'}
];

const rankOptions = [
  {'label': '2'},
  {'label': '3'},
  {'label': '4'},
  {'label': '5'},
  {'label': '6'},
  {'label': '7'},
  {'label': '8'},
  {'label': '9'},
  {'label': '10'},
  {'label': 'Jack'},
  {'label': 'Queen'},
  {'label': 'King'},
  {'label': 'Ace'}
];

const typeOptions = [
  {'label': 'Standard', 'value': 'normal'},
  {'label': 'Bonus', 'value': 'bonus'},
  {'label': 'Mult', 'value': 'mult'},
  {'label': 'Wild', 'value': 'wild'},
  {'label': 'Glass', 'value': 'glass'},
  {'label': 'Steel', 'value': 'steel'},
  {'label': 'Stone', 'value': 'stone'},
  {'label': 'Gold', 'value': 'gold'},
  {'label': 'Lucky', 'value': 'lucky'}
];

const sealOptions = [
  {'label': 'None', 'value': undefined},
  {'label': 'Gold', 'value': 'gold'},
  {'label': 'Red', 'value': 'red'},
  {'label': 'Blue', 'value': 'blue'},
  {'label': 'Purple', 'value': 'purple'}
];

const jokerOptions = [
  {'label': 'Joker', 'value': 'jimbo'},
  {'label': 'Greedy Joker', 'value': 'greedyJoker'},
  {'label': 'Lusty Joker', 'value': 'lustyJoker'},
  {'label': 'Wrathful Joker', 'value': 'wrathfulJoker'},
  {'label': 'Gluttonous Joker', 'value': 'gluttonousJoker'},
  {'label': 'Jolly Joker', 'value': 'jollyJoker'},
  {'label': 'Zany Joker', 'value': 'zanyJoker'},
  {'label': 'Mad Joker', 'value': 'madJoker'},
  {'label': 'Crazy Joker', 'value': 'crazyJoker'},
  {'label': 'Droll Joker', 'value': 'drollJoker'},
  {'label': 'Sly Joker', 'value': 'slyJoker'},
  {'label': 'Wily Joker', 'value': 'wilyJoker'},
  {'label': 'Clever Joker', 'value': 'cleverJoker'},
  {'label': 'Devious Joker', 'value': 'deviousJoker'},
  {'label': 'Crafty Joker', 'value': 'craftyJoker'},
  {'label': 'Half Joker', 'value': 'halfJoker'},
  {'label': 'Joker Stencil', 'value': 'jokerStencil'},
  {'label': 'Four Fingers', 'value': 'fourFingers'},
  {'label': 'Mime', 'value': 'mime'},
  {'label': 'Credit Card', 'value': 'creditCard'},
  {'label': 'Ceremonial Dagger', 'value': 'ceremonialDagger'},
  {'label': 'Banner', 'value': 'banner'},
  {'label': 'Mystic Summit', 'value': 'mysticSummit'},
  {'label': 'Marble Joker', 'value': 'marbleJoker'},
  {'label': 'Loyalty Card', 'value': 'loyaltyCard'},
  {'label': '8 Ball', 'value': '8Ball'},
  {'label': 'Misprint', 'value': 'misprint'},
  {'label': 'Dusk', 'value': 'dusk'},
  {'label': 'Raised Fist', 'value': 'raisedFist'},
  {'label': 'Chaos the Clown', 'value': 'chaosTheClown'},
  {'label': 'Fibonacci', 'value': 'fibonacci'},
  {'label': 'Steel Joker', 'value': 'steelJoker'},
  {'label': 'Scary Face', 'value': 'scaryFace'},
  {'label': 'Abstract Joker', 'value': 'abstractJoker'},
  {'label': 'Delayed Gratification', 'value': 'delayedGratification'},
  {'label': 'Hack', 'value': 'hack'},
  {'label': 'Pareidolia', 'value': 'pareidolia'},
  {'label': 'Gros Michel', 'value': 'grosMichel'},
  {'label': 'Even Steven', 'value': 'evenSteven'},
  {'label': 'Odd Todd', 'value': 'oddTodd'},
  {'label': 'Scholar', 'value': 'scholar'},
  {'label': 'Business Card', 'value': 'businessCard'},
  {'label': 'Supernova', 'value': 'supernova'},
  {'label': 'Ride the Bus', 'value': 'rideTheBus'},
  {'label': 'Space Joker', 'value': 'spaceJoker'},
  {'label': 'Egg', 'value': 'egg'},
  {'label': 'Burglar', 'value': 'burglar'},
  {'label': 'Blackboard', 'value': 'blackboard'},
  {'label': 'Runner', 'value': 'runner'},
  {'label': 'Ice Cream', 'value': 'iceCream'},
  {'label': 'DNA', 'value': 'dna'},
  {'label': 'Splash', 'value': 'splash'},
  {'label': 'Blue Joker', 'value': 'blueJoker'},
  {'label': 'Sixth Sense', 'value': 'sixthSense'},
  {'label': 'Constellation', 'value': 'constellation'},
  {'label': 'Hiker', 'value': 'hiker'},
  {'label': 'Faceless Joker', 'value': 'facelessJoker'},
  {'label': 'Green Joker', 'value': 'greenJoker'},
  {'label': 'Superposition', 'value': 'superposition'},
  {'label': 'To Do List', 'value': 'toDoList'},
  {'label': 'Cavendish', 'value': 'cavendish'},
  {'label': 'Card Sharp', 'value': 'cardSharp'},
  {'label': 'Red Card', 'value': 'redCard'},
  {'label': 'Madness', 'value': 'madness'},
  {'label': 'Square Joker', 'value': 'squareJoker'},
  {'label': 'Séance', 'value': 'seance'},
  {'label': 'Riff-Raff', 'value': 'riffRaff'},
  {'label': 'Vampire', 'value': 'vampire'},
  {'label': 'Shortcut', 'value': 'shortcut'},
  {'label': 'Hologram', 'value': 'hologram'},
  {'label': 'Vagabond', 'value': 'vagabond'},
  {'label': 'Baron', 'value': 'baron'},
  {'label': 'Cloud 9', 'value': 'cloud9'},
  {'label': 'Rocket', 'value': 'rocket'},
  {'label': 'Obelisk', 'value': 'obelisk'},
  {'label': 'Midas Mask', 'value': 'midasMask'},
  {'label': 'Luchador', 'value': 'luchador'},
  {'label': 'Photograph', 'value': 'photograph'},
  {'label': 'Gift Card', 'value': 'giftCard'},
  {'label': 'Turtle Bean', 'value': 'turtleBean'},
  {'label': 'Erosion', 'value': 'erosion'},
  {'label': 'Reserved Parking', 'value': 'reservedParking'},
  {'label': 'Mail-In Rebate', 'value': 'mailInRebate'},
  {'label': 'To the Moon', 'value': 'toTheMoon'},
  {'label': 'Hallucination', 'value': 'hallucination'},
  {'label': 'Fortune Teller', 'value': 'fortuneTeller'},
  {'label': 'Juggler', 'value': 'juggler'},
  {'label': 'Drunkard', 'value': 'drunkard'},
  {'label': 'Stone Joker', 'value': 'stoneJoker'},
  {'label': 'Golden Joker', 'value': 'goldenJoker'},
  {'label': 'Lucky Cat', 'value': 'luckyCat'},
  {'label': 'Baseball Card', 'value': 'baseballCard'},
  {'label': 'Bull', 'value': 'bull'},
  {'label': 'Diet Cola', 'value': 'dietCola'},
  {'label': 'Trading Card', 'value': 'tradingCard'},
  {'label': 'Flash Card', 'value': 'flashCard'},
  {'label': 'Popcorn', 'value': 'popcorn'},
  {'label': 'Spare Trousers', 'value': 'spareTrousers'},
  {'label': 'Ancient Joker', 'value': 'ancientJoker'},
  {'label': 'Ramen', 'value': 'ramen'},
  {'label': 'Walkie Talkie', 'value': 'walkieTalkie'},
  {'label': 'Seltzer', 'value': 'seltzer'},
  {'label': 'Castle', 'value': 'castle'},
  {'label': 'Smiley Face', 'value': 'smileyFace'},
  {'label': 'Campfire', 'value': 'campfire'},
  {'label': 'Golden Ticket', 'value': 'goldenTicket'},
  {'label': 'Mr. Bones', 'value': 'mrBones'},
  {'label': 'Acrobat', 'value': 'acrobat'},
  {'label': 'Sock and Buskin', 'value': 'sockAndBuskin'},
  {'label': 'Swashbuckler', 'value': 'swashbuckler'},
  {'label': 'Troubadour', 'value': 'troubadour'},
  {'label': 'Certificate', 'value': 'certificate'},
  {'label': 'Smeared Joker', 'value': 'smearedJoker'},
  {'label': 'Throwback', 'value': 'throwback'},
  {'label': 'Hanging Chad', 'value': 'hangingChad'},
  {'label': 'Rough Gem', 'value': 'roughGem'},
  {'label': 'Bloodstone', 'value': 'bloodstone'},
  {'label': 'Arrowhead', 'value': 'arrowhead'},
  {'label': 'Onyx Agate', 'value': 'onyxAgate'},
  {'label': 'Glass Joker', 'value': 'glassJoker'},
  {'label': 'Showman', 'value': 'showman'},
  {'label': 'Flower Pot', 'value': 'flowerPot'},
  {'label': 'Blueprint', 'value': 'blueprint'},
  {'label': 'Wee Joker', 'value': 'weeJoker'},
  {'label': 'Merry Andy', 'value': 'merryAndy'},
  {'label': 'Oops! All 6s', 'value': 'oopsAll6s'},
  {'label': 'The Idol', 'value': 'theIdol'},
  {'label': 'Seeing Double', 'value': 'seeingDouble'},
  {'label': 'Matador', 'value': 'matador'},
  {'label': 'Hit the Road', 'value': 'hitTheRoad'},
  {'label': 'The Duo', 'value': 'theDuo'},
  {'label': 'The Trio', 'value': 'theTrio'},
  {'label': 'The Family', 'value': 'theFamily'},
  {'label': 'The Order', 'value': 'theOrder'},
  {'label': 'The Tribe', 'value': 'theTribe'},
  {'label': 'Stuntman', 'value': 'stuntman'},
  {'label': 'Invisible Joker', 'value': 'invisibleJoker'},
  {'label': 'Brainstorm', 'value': 'brainstorm'},
  {'label': 'Satellite', 'value': 'satellite'},
  {'label': 'Shoot the Moon', 'value': 'shootTheMoon'},
  {'label': 'Driver\'s License', 'value': 'driversLicense'},
  {'label': 'Cartomancer', 'value': 'cartomancer'},
  {'label': 'Astronomer', 'value': 'astronomer'},
  {'label': 'Burnt Joker', 'value': 'burntJoker'},
  {'label': 'Bootstraps', 'value': 'bootstraps'},
  {'label': 'Canio', 'value': 'canio'},
  {'label': 'Triboulet', 'value': 'triboulet'},
  {'label': 'Yorick', 'value': 'yorick'},
  {'label': 'Chicot', 'value': 'chicot'},
  {'label': 'Perkeo', 'value': 'perkeo'}
];

const lifespanOptions = [
  {'label': 'None', 'value': undefined},
  {'label': 'Eternal', 'value': 'eternal'},
  {'label': 'Perishable', 'value': 'perishable'}
];

const debuffOptions = [
  {'label': 'None', 'value': undefined},
  {'label': 'Rental', 'value': 'rental'}
];

export { suitOptions, rankOptions, typeOptions, sealOptions, jokerOptions, lifespanOptions, debuffOptions};